library(rJava)
library(DBI)
library(RJDBC)
library(XML)
library(memoise)
library(KoNLP)
library(wordcloud)
library(dplyr)
library(ggplot2)
library(ggmap)
library(rvest)
library(RColorBrewer)
library(data.table)
library(reshape)
getwd()
setwd("C:\\R\\project180721")
KoNLP::useSejongDic()
dSeoulNew<- readLines("seoul_new.txt")
class(dSeoulNew)
dSeoulNew<-sapply(dSeoulNew,extractNoun,USE.NAMES = T)
class(dSeoulNew)
dSeoulNew<-unlist(dSeoulNew)
class(dSeoulNew)
dSeoulNew<-gsub("\\d+","",dSeoulNew)
head(dSeoulNew)

